[build]
  publish = "."

[[redirects]]
  from = "/apply"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/invite"
  to = "/share.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"


[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200


[[redirects]]
  from = "/setup"
  to = "/setup.html"
  status = 200
